services:
  - type: web
    name: ne-don-energy
    env: docker
    dockerfilePath: Dockerfile
    region: frankfurt
    plan: free
    envVars:
      - key: APP_ENV
        value: production
      - key: APP_DEBUG
        value: false
      - key: COMPOSER_ALLOW_SUPERUSER
        value: "1"
      - key: PHP_MEMORY_LIMIT
        value: "512M"
      - key: NODE_ENV
        value: production
    disk:
      name: data
      mountPath: /app/storage
      sizeGB: 1
    healthCheckPath: /
