services:
  - type: web
    name: ne-don-energy
    env: php
    region: frankfurt
    plan: free
    buildCommand: |
      composer install --no-dev --optimize-autoloader
      npm install
      npm run build
      php artisan config:cache
      php artisan route:cache
      php artisan view:cache
    startCommand: heroku-php-apache2 public/
    envVars:
      - key: APP_ENV
        value: production
      - key: APP_DEBUG
        value: false
      - key: COMPOSER_ALLOW_SUPERUSER
        value: "1"
      - key: PHP_VERSION
        value: "8.0"
      - key: NODE_VERSION
        value: "16.x"
      - key: NPM_VERSION
        value: "8.x"
      - key: PHP_MEMORY_LIMIT
        value: "512M"
      - key: APP_URL
        sync: true
      - key: APP_KEY
        generateValue: true
    disk:
      name: data
      mountPath: /opt/render/project/src/storage
      sizeGB: 1
    healthCheckPath: /
    autoDeploy: true
