services:
  - type: web
    name: ne-don-energy
    env: docker
    dockerfilePath: Dockerfile
    region: frankfurt
    plan: free
    buildCommand: docker build --no-cache .
    startCommand: ""
    envVars:
      - key: APP_ENV
        value: production
      - key: APP_DEBUG
        value: false
      - key: COMPOSER_ALLOW_SUPERUSER
        value: "1"
      - key: PHP_MEMORY_LIMIT
        value: "512M"
      - key: NODE_ENV
        value: production
      - key: DOCKER_BUILDKIT
        value: "1"
      - key: APACHE_DOCUMENT_ROOT
        value: /var/www/html/public
    disk:
      name: data
      mountPath: /var/www/html/storage
      sizeGB: 1
    healthCheckPath: /
    buildFilter:
      paths:
        - app/**/*.php
        - config/**/*.php
        - public/**/*
        - resources/**/*
        - routes/**/*.php
        - composer.*
        - package.json
