services:
  - type: web
    name: ne-don-energy
    env: docker
    dockerfilePath: Dockerfile
    region: frankfurt
    plan: free
    buildCommand: docker build --build-arg BUILDKIT_INLINE_CACHE=1 .
    envVars:
      - key: APP_ENV
        value: production
      - key: APP_DEBUG
        value: false
      - key: COMPOSER_ALLOW_SUPERUSER
        value: 1
      - key: COMPOSER_MEMORY_LIMIT
        value: -1
      - key: PHP_VERSION
        value: 8.0.2
      - key: NODE_ENV
        value: production
      - key: DOCKER_BUILDKIT
        value: 1
    healthCheckPath: /
    buildFilter:
      paths:
        - app/**/*.php
        - config/**/*.php
        - public/**/*
        - resources/**/*
        - routes/**/*.php
        - composer.*
        - package.json
