services:
  - type: web
    name: ne-don-energy
    env: php
    region: frankfurt
    plan: free
    buildCommand: |
      composer install --no-dev --optimize-autoloader --no-interaction
      npm install
      npm run build
      mkdir -p storage/framework/{sessions,views,cache}
      mkdir -p bootstrap/cache
      chmod -R 777 storage bootstrap/cache
      cp .env.example .env
      php artisan key:generate
      php artisan storage:link
      php artisan config:clear
      php artisan cache:clear
      php artisan config:cache
      php artisan route:cache
      php artisan view:cache
    startCommand: vendor/bin/heroku-php-apache2 public/
    envVars:
      - key: APP_NAME
        value: NE-Don-Energy
      - key: APP_ENV
        value: production
      - key: APP_DEBUG
        value: false
      - key: APP_KEY
        generateValue: true
      - key: APP_URL
        value: https://crefer-togo.onrender.com
      - key: LOG_CHANNEL
        value: stderr
      - key: DB_CONNECTION
        value: pgsql
      - key: SESSION_DRIVER
        value: file
      - key: CACHE_DRIVER
        value: file
      - key: QUEUE_CONNECTION
        value: sync
      - key: FILESYSTEM_DISK
        value: public
      - key: PHP_VERSION
        value: "8.0"
      - key: COMPOSER_VERSION
        value: "2.5.8"
      - key: NODE_VERSION
        value: "16.x"
    healthCheckPath: /
    disk:
      name: storage-disk
      mountPath: /opt/render/project/src/storage
      sizeGB: 1
