services:
  - type: web
    name: don-energy    env: php
    buildCommand: |
      composer install --no-dev --optimize-autoloader &&
      npm install &&
      npm run build &&
      php artisan config:cache &&
      php artisan route:cache &&
      php artisan view:cache
    startCommand: bash -c "php artisan migrate --force && vendor/bin/heroku-php-apache2 public/"
    envVars:
      - key: APP_ENV
        value: production
      - key: APP_DEBUG
        value: false
      - key: APP_KEY
        generateValue: true
      - key: DB_CONNECTION
        value: pgsql
      - key: DB_HOST
        fromDatabase:
          name: don-energy-db
          property: host
      - key: DB_PORT
        fromDatabase:
          name: don-energy-db
          property: port
      - key: DB_DATABASE
        fromDatabase:
          name: don-energy-db
          property: database
      - key: DB_USERNAME
        fromDatabase:
          name: don-energy-db
          property: username
      - key: DB_PASSWORD
        fromDatabase:
          name: don-energy-db
          property: password

databases:
  - name: don-energy-db
    plan: free
