services:
  - type: web
    name: ne-don-energy
    env: php
    region: frankfurt
    plan: free
    runtime: php
    buildCommand: |
      mkdir -p storage/framework/{sessions,views,cache}
      chmod -R 777 storage bootstrap/cache
      composer install --no-dev --optimize-autoloader --no-interaction
      npm install
      npm run build
    startCommand: |
      php artisan config:cache
      php artisan route:cache
      php artisan view:cache
      heroku-php-apache2 public/
    envVars:
      - key: APP_NAME
        value: NE-Don-Energy
      - key: APP_ENV
        value: production
      - key: APP_KEY
        generateValue: true
      - key: APP_DEBUG
        value: false
      - key: APP_URL
        sync: true
      - key: LOG_CHANNEL
        value: stderr
      - key: DB_CONNECTION
        value: pgsql
      - key: SESSION_DRIVER
        value: file
      - key: CACHE_DRIVER
        value: file
      - key: QUEUE_CONNECTION
        value: sync
