services:
  - type: web
    name: crefer-togo
    env: php
    buildCommand: |
      composer install --no-dev --optimize-autoloader &&
      npm ci &&
      npm run build &&
      cp env.production .env &&
      mkdir -p storage/framework/{sessions,views,cache} storage/app/public &&
      php artisan storage:link &&
      php artisan key:generate &&
      chmod +x post-build.sh &&
      ./post-build.sh
    startCommand: |
      php -S 0.0.0.0:$PORT -t public
    envVars:
      - key: APP_ENV
        value: production
      - key: APP_DEBUG
        value: false
      - key: APP_KEY
        generateValue: true
      - key: DB_CONNECTION
        value: pgsql
      - key: DB_HOST
        fromDatabase:
          name: don-energy-db
          property: host
      - key: DB_PORT
        fromDatabase:
          name: don-energy-db
          property: port
      - key: DB_DATABASE
        fromDatabase:
          name: don-energy-db
          property: database
      - key: DB_USERNAME
        fromDatabase:
          name: don-energy-db
          property: username
      - key: DB_PASSWORD
        fromDatabase:
          name: don-energy-db
          property: password

databases:
  - name: don-energy-db
    plan: free
