services:
  - type: web
    name: don-energy    env: php
    runtime: php    buildCommand: |
      mkdir -p storage/framework/{sessions,views,cache} &&
      composer install --no-dev --optimize-autoloader &&
      npm install &&
      npm run build &&
      cp .env.example .env &&
      php artisan key:generate &&
      chmod -R 777 storage bootstrap/cache
    startCommand: bash -c "php artisan storage:link && php artisan migrate --force && php artisan serve --host=0.0.0.0 --port=$PORT"
    envVars:
      - key: APP_ENV
        value: production
      - key: APP_DEBUG
        value: false
      - key: APP_KEY
        generateValue: true
      - key: DB_CONNECTION
        value: pgsql
      - key: DB_HOST
        fromDatabase:
          name: don-energy-db
          property: host
      - key: DB_PORT
        fromDatabase:
          name: don-energy-db
          property: port
      - key: DB_DATABASE
        fromDatabase:
          name: don-energy-db
          property: database
      - key: DB_USERNAME
        fromDatabase:
          name: don-energy-db
          property: username
      - key: DB_PASSWORD
        fromDatabase:
          name: don-energy-db
          property: password

databases:
  - name: don-energy-db
    plan: free
